name: ${CONTAINER_NAME}

services:
  Jellyfin:
    # Container
    container_name: ${CONTAINER_NAME}
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    
    # Security
    security_opt:
      - no-new-privileges:true

    # Networking
    hostname: ${CONTAINER_NAME}
    networks:
      - traefik
    ports:
      - "8096:8096" 
   
   # Mounts
    volumes:
      - ./config:/config
      - /Storage/30-39_Video/31_Filme:/data/movies:ro
      - /Storage/30-39_Video/32_Sendungen:/data/tvshows:ro

    devices:
      - /dev/some_device:/dev/some_device
    
    # Miscellaneous
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      #- JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.monitor-only=true" # Comment to automatically update via Watchtower (enabled by default)
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik-rtr.entrypoints=https"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.$DOMAINNAME`)"
      - "traefik.http.routers.traefik-rtr.tls=true"
      - "traefik.http.routers.traefik-rtr.tls.certresolver=dns-netcup"
      - "traefik.http.routers.traefik-rtr.tls.domains[0].main=$DOMAINNAME"
      - "traefik.http.routers.traefik-rtr.tls.domains[0].sans=*.$DOMAINNAME"
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      - "traefik.http.routers.traefik-rtr.middlewares=middlewares-basic-auth@file"

networks:
  traefik:
    external: true